Project Setup
Dandush03/JS-RestaurantPage pull request #1
Opened 2020-04-16 13:17 UTC by Dandush03

Adding script and basic HTML structure
Created CSS file

2020-04-17 23:29 UTC, jofer86 requested changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- Firstly we need to modularize our code a little bit more, even though you are doing the correct thing appending the components to your main div, the entire app should be constructed with modules, and every module needs to export the component. IE using the export import syntax. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png)
- The module exports need to export, aside from the content, the styles, now you could take two approaches here, do the styling individually for each module, and have those files live in a separate folder and have them come together, or you could do your styling inside your JS files.

# `Project Status: Almost There!` :goal_net: :goal_net: :goal_net: 

--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-04-19 00:16 UTC, Dandush03 commented
# Hey! Don't know  how i miss that hehe.

It is done, I modulated my code as much as I could.

Hope I did a good job.

##### Looking forward for your next review

2020-04-19 00:17 UTC, Dandush03 commented
# Hey!
## Don't know  how i miss that hehe. :wink: 

It is done, I modulated my code as much as I could.

Hope I did a good job.

##### Looking forward for your next review

2020-04-20 14:59 UTC, shloch requested changes
## hello @Dandush03 

We're good to go, great job............

### [Required Changes]
Let's just use the correct linting file and we're good to go
### Happy coding

2020-04-20 14:59 UTC, shloch commented on .eslintrc.json
> +}
Please use the linting config file provided by MICROVERSE --> [ [see config](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json) ]

2020-04-20 16:14 UTC, Dandush03 commented
# HEY!!! :wave: 

## Thanks for you review.

#### I hope you understand that you asking me to disable some rule wich actually will not change ANYTHING on my project. :weary: 

# Have a good day. 

# Happy Coding :computer:

2020-04-20 17:58 UTC, azdrenymeri approved these changes
### Hello @Dandush03  :wave: 
#### The linter `config` is done correctly. :heavy_check_mark: 
#### You can merge it :+1:

2020-04-20 20:28 UTC, merged